---
apiVersion: v1
kind: Pod
metadata:
  labels:
    env: backend
spec:
  containers:
    - name: httpd
      image: httpd:latest

---
apiVersion: v1
kind: Pod
metadata:
  labels:
    env: frontend
spec:
  containers:
    - name: web
      image: nginx:latest