---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: demo-rs
spec:
  replicas: 3
  selector:
    metaLabels:
       tier: backend
    template:
      metadata:
        name: sample-pod
        labels:
          tier: backend
      spec:
        containers:
          name: nginx
          image: nginx 