apiVersion: v1
kind: Pod
metadata: 
   name: configmap-demo-pod
   namespace: cm-test-ns
spec:
  containers:
  - name: cm-container
    image: alpine
    command: [ "sleep", "1d" ]
    envFrom:
      - configMapRef:
          name: cm-demo
